### ISSUE TITLE
2-pin tactile switch link in BOM

### ISSUE THREAD

**Issue by 3amorphousblobs** [PaulKlinger/rps-rnn#1]
your BOM links to the same 4-pin switches for the start button as it does for the 3 other buttons.

**Comment by PaulKlinger** [comment]
Thanks for the heads up, sorry I didn't see your comment before.

I've corrected the link, it should have pointed [here](https://www.aliexpress.com/item/32752118872.html).

(There isn't really any reason for using two different switches, I mostly wanted to try both of them out.)

**Comment by 3amorphousblobs** [comment]
Just got my first board populated/programmed and it works great! Awesome
project, I'll be giving out a bunch of these to coworkers, friends, etc.

**Comment by PaulKlinger** [comment]
That's awesome, this is the first time someone else actually built one of my projects! Please take some pictures :D

**Comment by 3amorphousblobs** [comment]
Here's the first one. I used super glue instead of the optical fiber for
the led diffusers. Other than that i followed all your instructions.

**Comment by PaulKlinger** [comment]
The image didn't show up unfortunately, I think github just ignores email attachments.

**Comment by 3amorphousblobs** [comment]
Shoot, if you give me another email address ill send pics there

**Comment by PaulKlinger** [comment]
klinger.paul@gmail.com (or you can upload a file to the issue on the github website)

**Comment by 3amorphousblobs** [comment]
[received_269599187256696.zip](https://github.com/PaulKlinger/rps-rnn/files/3647655/received_269599187256696.zip)

**Comment by PaulKlinger** [comment]
Awesome :D

Did you have any issues building them? Maybe some things to change for v2?
